apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: lstm
  name: lstm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lstm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: lstm
    spec:
      containers:
      - image: siri0000/lstm_model_image:13
        name: lstm
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: lstm